spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        type: trace

# Server SSL 적용
server:
  ssl:
    key-store: keystore.p12
    key-store-password: 1033489
    keyStoreType: PKCS12
    keyAlias: tomcat
    
# Facebook oAuth 2.0 configure
facebook:
  client:
    clientId: 214940482748221
    clientSecret: 41881ee1424a2361e508e24311217db2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=email,name,picture

# Google oAuth 2.0 configure
google :
  client :
    clientId : 179989071524-gn841s6e7c72793tmjvf2q68jhqau0bo.apps.googleusercontent.com
    clientSecret: pDra-ML0oHyEQDsL8rEwbBXY
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo